### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by TobiaszCudnik** [covidpass-org/covidpass#102]
Neither the file nor camera scanning work on ios 14. Please dont waste ppls time.

Its not that hard to scan qr codes in 2021, really.

> Note that selecting a file directly from camera is not supported.

Completely dumb sentence.

**Comment by JantsoP** [comment]
There are issues with for example iPhone 6 users.
You must use Safari to use service. Also, check issue #42

**Comment by marvinsxtr** [comment]
Please reopen if there is a problem and be nice.
