### ISSUE TITLE
Use the new iOS 15 Wallet 

### ISSUE THREAD

**Issue by iMonZ** [covidpass-org/covidpass#104]
In iOS 15 we got a new wallet module for vaccine certificates.
You could actually replace your old one with this:

https://www.computerbild.de/artikel/cb-News-App-Check-iOS-15.1-Impfnachweis-wandert-in-die-Wallet-30805397.html

**Comment by iMonZ** [comment]
https://developer.apple.com/news/?id=7h3vwlh5

**Comment by Ein-Tim** [comment]
Please see https://github.com/covidpass-org/covidpass/issues/75#issuecomment-924334367 & https://github.com/corona-warn-app/cwa-app-ios/issues/2965#issuecomment-925176909. 

This doesn't help here.

**Comment by iMonZ** [comment]
@Ein-Tim thanks

**Comment by iMonZ** [comment]
@Ein-Tim thanks
