### ISSUE TITLE
[Feature request] add EU blue and EU DCC logo

### ISSUE THREAD

**Issue by MoienBowen** [covidpass-org/covidpass#112]
Hi Marvin,
I really appreciate your work and the design and the information shown on the pass.

1. Could you please add the EU blue as one of the colour choices?

According to [Graphics guide to the European emblem](https://publications.europa.eu/code/en/en-5000100.htm), the reflex blue is 003399.

2. I understand that you may wanna keep your original idea as a part of the pass. But do you consider to use the logo of official repo of EU DCC (on the top left), please?

Here is the [EU DCC Repo](https://github.com/eu-digital-green-certificates), and the logo is found to be used on [this page](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en) 

3. Although people may be calling the certificate as a pass, but the official name is EU Digital COVID Certificate (and short version is EU DCC). 

Will you change the title to this official name on the top left? (I saw someone can display two lines text on that corner, if not possible, you can use the short version.)

In this case, the type on the top right can also use the official name: Vaccination certificate, Test certificate and Recovery certificate.

Thanks again for your project. :)

**Comment by marvinsxtr** [comment]
Thank you for the request. As I already explained in a previous issue, my intent was to make the pass look unofficial as I do not want to imitate official EU documents. Feel free to fork this repository to create your personal custom pass though.
