### ISSUE TITLE
Not working with third dose health pass

### ISSUE THREAD

**Issue by Jo-Panic** [covidpass-org/covidpass#124]
Hello,

It seems that it does not work with a 3rd dose health pass. I have the message : Invalid QR code (for French health pass, Safari on iOS 15).

Thanks.

**Comment by marvinsxtr** [comment]
I got similar reports for German passes.

**Comment by chteuchteu** [comment]
Experiencing the same issue here ("QR Code non valide")

**Comment by ErJah** [comment]
Hello,
Got the same issue for my third jab.
Is there any ETA on this issue ?
Can't get my old certificate back and got to search for my pdf on the phone every time 😕 thanks 👍🏻

**Comment by marvinsxtr** [comment]
To fix this, I have to reproduce it. Also I can't just ask you to send me your certificate. So no ETA unfortunately.

**Comment by chteuchteu** [comment]
Is there any way for us to help you on that? I could open a PR to fix this issue: is there any documentation on the part that may be in cause?

**Comment by marvinsxtr** [comment]
If I had to guess, the problem is likely in src/payload.ts. Most parts of the code are documented but we do not have a separate documentation atm.

**Comment by wifwucite** [comment]
I just found something interesting: Today I got my 3rd vaccination shot and a corresponding certificate. Importing it into the "Corona-Warn" App worked fine. Checking it with that app also worked fine. However, scanning the same certificate with the "CovPassCheck" app yielded an error message: "Zertifikat erfüllt nicht alle Bedingungen" (certificate does not fulfil all requirements). Could that be a cause of the issue?
Or is this just something with my certificate?

**Comment by wifwucite** [comment]
Strrrrrike: I got it working: Open your certificate in the "Corona-Warn" App, take a screen capture of the QR code, navigate to the [website](https://covidpass.marvinsextro.de/), open the screen capture, generate and import the card into your wallet. Enjoy! :-)

**Comment by julien1619** [comment]
I managed to fix it. The QR Code has a new format : `https://bonjour.tousanticovid[..../...]#[Here is the certificate]`. The certificate is URI encoded in the hash. I've created a PR to fix it #136.

**Comment by SHASKAN57** [comment]
Hi !

Any news about this issue guys ?
