### ISSUE TITLE
Add  "Save to Google Pay" button

### ISSUE THREAD

**Issue by jvmonjo** [covidpass-org/covidpass#125]
To avoid using a third party wallet application in Android, it would be nice to add a "Save to Google Pay" button to integrate the covid pass directly into Google Pay app.

If somebody has the time to make a PR, here is the [API](https://developers.google.com/pay/passes/guides/implement-the-api/save-passes-to-google-pay?feed=web-button#feed)

**Comment by marvinsxtr** [comment]
See #131

**Comment by marvinsxtr** [comment]
> When a user clicks the button, a JSON Web Token (JWT) that represents their Pass is sent to Google servers.

I don't like this part...
