### ISSUE TITLE
Check CovidPassApiNet

### ISSUE THREAD

**Issue by agustinpallares94** [covidpass-org/covidpass#129]
I had some problems running CovidPassApiNet. I noticed that the repository is not very active, could you comment here the failures I got?

Thank you so much

**Comment by marvinsxtr** [comment]
I would suggest that you open an issue with the problem description in the CovidPassApiNet repository.

**Comment by agustinpallares94** [comment]
> I would suggest that you open an issue with the problem description in the CovidPassApiNet repository.

Okay! Thank you!
