### ISSUE TITLE
Issue with Apple Watch Series 7

### ISSUE THREAD

**Issue by fabrilord** [covidpass-org/covidpass#132]
Hi,
QR Code right corners appear cutted on Apple Watch Series 7 display, then QR Code readers can’t read it.
Can you please fix this?
Thanks!

**Comment by marvinsxtr** [comment]
Unfortunately, CovidPass has no influence on how watchOS displays QR codes. You could probably open a bug report or a discussion about this on the Apple Developer Forum.
