### ISSUE TITLE
Hide name option

### ISSUE THREAD

**Issue by V0l-D** [covidpass-org/covidpass#137]
Could you make a option to hide the name, in the Netherlands they do this and this would be more privacy friendly in my eyes.

**Comment by marvinsxtr** [comment]
While this may be privacy friendly, the name is needed to check with the ID of the certificate holder in order to verify its validity.

**Comment by V0l-D** [comment]
> While this may be privacy friendly, the name is needed to check with the ID of the certificate holder in order to verify its validity.

You can do this by showing the first 2 letters, date of month etc. They do this in the Netherlands already as shown here:

![image](https://user-images.githubusercontent.com/35117713/145659883-27325162-9c4f-472d-8b07-32618e85a6e2.png)

(The image shown above is from Dutch corona check website as a example)
