### ISSUE TITLE
Link to Apple privacy note does not work

### ISSUE THREAD

**Issue by Ein-Tim** [covidpass-org/covidpass#145]
Clicking on https://covidpass.marvinsextro.de/de-DE/privacy on the last link "Datenschutz" (Apple) links to https://www.apple.com/legal/privacy/en-ww/privacy.tsx. This link does not work. The correct one is: https://www.apple.com/legal/privacy/de-ww/ (for the German version).

**Comment by marvinsxtr** [comment]
Fixed with #147.
