### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by eringobraghless** [covidpass-org/covidpass#161]
Hi, I used your website to add my original vaccine certs, now I wanted to upload my booster but it doesnt seem to work. The camera, upload file, colour selector, and the sponsor button as well dont do anything. They do appear highlighted when clicked but nothing else happens. The only things I could click were the privacy policy and the bottom links (like to the github). Thank you

**Comment by Ein-Tim** [comment]
Same as #35?

**Comment by eringobraghless** [comment]
I have an iphone SE 2 (just over a year old) and ios 14.7.1, do you think it could be that i havent updated to ios 15?

**Comment by eringobraghless** [comment]
it was working for me in august when i got my second dose

**Comment by eringobraghless** [comment]
i just updated… the site works. im very sorry to have wasted your time. maybe it just doesnt work with older ios software altogether
