### ISSUE TITLE
Server error: “Connection is not in private mode”

### ISSUE THREAD

**Issue by Its7ede** [covidpass-org/covidpass#165]
The browser retrievers a security error: “ Connection is not in private mode” and I can’t go on. It’s look like website certificates are not valid anymore.

**Comment by papalii** [comment]
It also happens to me since yesterday, on Safari, Firefox and Google Chrome.
Safari reports this as an untrusted certificate with expiry March 26th 2022.
3 days ago it worked.

**Comment by Ein-Tim** [comment]
Confirm issue, seems to be a problem with the certificate, here is a screenshot from Safari:

<img src="https://user-images.githubusercontent.com/67682506/151657365-3178116a-d132-4e5c-a236-1f7ee7cae46b.jpeg" width="300">

FYI: @marvinsxtr

**Comment by marvinsxtr** [comment]
Should be fixed. For anyone interested, [this](https://community.letsencrypt.org/t/questions-about-renewing-before-tls-alpn-01-revocations/170449) was the cause.
