### ISSUE TITLE
Buttons don't work in iOS 14.5

### ISSUE THREAD

**Issue by MagicLegend** [covidpass-org/covidpass#169]
Hi!

All buttons on the site _except for the Add to Wallet button_ don't work anymore on my iOS 14.5 device. On my gfs iOS 15 device it is fine though. I am able to reproduce the issue in Browserstack on an iOS 14 device, so I'm assuming it's not just my device.

A fix would be very much appreciated!

**Comment by Ein-Tim** [comment]
Same as #35.

**Comment by MagicLegend** [comment]
@Ein-Tim You are totally right, my bad! I'll close this issue in favor of #35.
