### ISSUE TITLE
Reference to iOS 15.4 feature to store EU DCCs in Wallet (and Health)?

### ISSUE THREAD

**Issue by Ein-Tim** [covidpass-org/covidpass#176]
I think it would make sense to include a hint that a vaccination certificate can also be stored in the Apple Wallet without using this tool by scanning the QR code with the native iOS camera and adding it to Health & Wallet.
Do you plan to include this?

**Comment by Ein-Tim** [comment]
No answer, OK.

**Comment by marvinsxtr** [comment]
Since the tool is barely used anymore and my Developer Certificates are about to expire, I would replace the content of the site with the proposed reference for now. After that I would probably archive the repo.

**Comment by Ein-Tim** [comment]
@marvinsxtr That sounds good in my opinion! Let me know if I can help somehow!

**Comment by marvinsxtr** [comment]
I'm not sure about the content of the page yet, however it should probably reference this: https://support.apple.com/HT212752

**Comment by Ein-Tim** [comment]
@marvinsxtr Yep, definitely. Just quick and dirty how it could look: 
![Bildschirmfoto 2022-06-05 um 18 49 05](https://user-images.githubusercontent.com/67682506/172061337-b6304f02-f642-41a9-b18b-e5661114b66b.png)

**Comment by marvinsxtr** [comment]
The change should be visible soon, I forked the repo at https://github.com/marvinsxtr/covidpass. I might also add the note to the readme of this repository.

**Comment by Ein-Tim** [comment]
@marvinsxtr Sounds gold! Thank you!

**Comment by Ein-Tim** [comment]
New text is live, this issue can be closed.
