### ISSUE TITLE
Certificate not shown on ios lock screen

### ISSUE THREAD

**Issue by olfway** [covidpass-org/covidpass#25]
Some boarding and other passes shown if I open wallet from lock screen,
but unfortunately I had to unlock my phone and open wallet app to see my vaccination certificate.

Could you, please, add an option to show certificate without unlocking?

**Comment by marvinsxtr** [comment]
This can be changed in the [settings](https://support.apple.com/guide/iphone/control-access-information-lock-screen-iph9a2a69136/ios).

**Comment by olfway** [comment]
I have wallet app enabled on lock screen, but vaccination certificate not present there

**Comment by olfway** [comment]
I just tried to generate fake boarding pass here https://www.passsource.com/pass/register.php?templateId=1&
It's shown on lock screen perfectly

**Comment by marvinsxtr** [comment]
Sorry for closing this early. So the pass is not present at all or just not if the phone is locked?

**Comment by olfway** [comment]
The pass is present if I unlock my phone and open wallet app,
but it's not present if I open wallet app with side-button double-click

**Comment by marvinsxtr** [comment]
You could try to delete the certificate and add it again, unfortunately I cannot reproduce this issue.

**Comment by olfway** [comment]
Just tried to remove and read it and now it works
Thanks!

**Comment by Ein-Tim** [comment]
I have the same issue on an iPhone 8, "Wallet" is active in Settings, deleting and adding again did not help. No other cards in Wallet.

**Comment by olfway** [comment]
I had only one credit card in wallet and certificate of vaccination wasn't present on lockscreen
After that I added several passes from the https://www.passsource.com (boarding pass, coupon, generic) - all of them were present on lockscreen, but not coronapass one
And then I removed coronapass and re-added it
