### ISSUE TITLE
undefined is not an object (evaluating 't.decodedData[-260].v[0]')

### ISSUE THREAD

**Issue by valids** [covidpass-org/covidpass#32]
The following error message is displayed in a red rectangle on the bottom of the page when I click Add to Wallet.
`undefined is not an object (evaluating 't.decodedData[-260].v[0]')`

I have the same error when using the camera and also when scanning the PDF.

It was working for vaccination QR codes (tested a couple of days ago).
It failed for the negative PCR-test result QR code (tested today, 08.07.21).

All QR codes I tested were officially generated by the authorities in Romania.
Tested on: https://covidpass.marvinsextro.de/

**Comment by Ein-Tim** [comment]
Which browser are you using? Safari?

**Comment by Ein-Tim** [comment]
You can't create wallet passes for test or recovery certificates at the moment. Does it work with vaccination certificates?

**Comment by valids** [comment]
> 
> 
> Which browser are you using? Safari?

Yes. In both cases: when it was working and when it failed.

**Comment by valids** [comment]
> 
> 
> You can't create wallet passes for test or recovery certificates at the moment. Does it work with vaccination certificates?

Yes. Thanks. Tomorrow we have a flight to Germany. Maybe PCR-test certificates support is available by then. :)

**Comment by Ein-Tim** [comment]
The corresponding issue for this is #5.

**Comment by marvinsxtr** [comment]
I will close this with reference to #5.

**Comment by marvinsxtr** [comment]
@valids You should now be able to add your test certificates. See #34

**Comment by valids** [comment]
> @valids You should now be able to add your test certificates. See #34

@marvinsxtr Thanks a lot. It works. Guys, did you sleep? I am leaving to DE now…
