### ISSUE TITLE
EU Members States' Digital COVID Certificate Insights

### ISSUE THREAD

**Issue by estamos** [covidpass-org/covidpass#33]
You can find some very useful insights for each EU member state at  [`eu-digital-green-certificates/dgc-testdata`](https://github.com/eu-digital-green-certificates/dgc-testdata), which is the Official GitHub Organization of the EU Digital COVID Certificates (EUDCC) project.

In addition, for EU member countries, it would be preferably to use EU flag with country's code placed in centre of 12 stars as a logo for the pass instead of current ✔️ CovidPass logo, as that's what most EU countries use at their COVID Certificate.

**Comment by marvinsxtr** [comment]
Thank you for the hint, I was looking for this. For the logo, I want to keep it looking unofficial as it is.
