### ISSUE TITLE
Scanner and file selector do not work on older iOS versions

### ISSUE THREAD

**Issue by marvinsxtr** [covidpass-org/covidpass#40]
This affects the iPhone 6 (plus) and iOS 12.5.4 or older.

**Comment by Ein-Tim** [comment]
Was this closed by accident? Or have you found a fix @marvinsxtr?

**Comment by marvinsxtr** [comment]
@Ein-Tim I just noticed we have this issue already. I can't really work on this because I don't own an older device.
