### ISSUE TITLE
Possibility to not suggest on lockscreen

### ISSUE THREAD

**Issue by leolelego** [covidpass-org/covidpass#41]
EU Covid QR code has a lot of info on you. Anyone finding your phone is able to see the CovidPass without unlock it. Just double tap on home or side button. 

Apple Wallet provide an option to "Suggest on Lockscreen" or not for some cards. It could be great to have this option so nobody can see our QR code without unlocking the phone. 

thanks for this nice web site by the way! 

Exemple here on my supermarket card.
![Untitled 2](https://user-images.githubusercontent.com/4069471/126319481-e568de87-a88b-4612-8488-0ee1cc64de4f.jpg)

**Comment by marvinsxtr** [comment]
Suggest on Lock Screen seems to show the pass based on time and location, which does not apply to CovidPass. You can restrict lock screen access for all passes in the settings. See [this guide](https://support.apple.com/guide/iphone/control-access-information-lock-screen-iph9a2a69136/ios).
