### ISSUE TITLE
Invalid Medical Product

### ISSUE THREAD

**Issue by Grendas** [covidpass-org/covidpass#44]
Adding a certificate with the vaccine type: Biontech - Comirnaty, fails to create the pass with message "Invalid Medical Product" .
The Astrazeneca vaccine works perfectly.

![Screenshot 2021-07-23 at 15 34 09](https://user-images.githubusercontent.com/30785103/126782219-c9b156d8-ae39-45c5-a11b-f198df4e619a.png)

**Comment by JantsoP** [comment]
I have Biontech - Comirnaty and it works fine. By the looks of it, you are trying to provide screenshot. I just tested with full picture of the certificate and not just QR code and worked fine. So this is something I cannot duplicate. You can also provide the actual .pdf (I got it as .pdf) to the system. Did you try that?

**Comment by mackonsti** [comment]
Hi @Grendas on a side note, together with your reply to @JantsoP can I ask you what you are getting as **displayed** name, too? Is it in Greek alphabet and capitals, as I had mentioned to @marvinsxtr in ticket #30 ? Thank you, ευχαριστώ.

**Comment by Grendas** [comment]
Hi @mackonsti , indeed the name is in Greek and capitals.

Hey @JantsoP , thanks for your answer. I have tried the actual .pdf of the certificate and I got "no QR code found".

![Screenshot 2021-07-23 at 19 42 38](https://user-images.githubusercontent.com/30785103/126814443-9c8d76f1-8cfb-486b-aedd-d97753a12311.png)

**Comment by mackonsti** [comment]
@Grendas I exported again the PDF from http://eudcc.gov.gr/ in case they had made the name appear in QR in Latin characters, as I need it for travelling (despite being shown in Latin on PDF) and it worked fine on mine. What platform are you using, iOS, Android, Windows, macOS to run http://covidpass.marvinsextro.de/ ? I used both macOS and iOS without hiccups.

**Comment by Grendas** [comment]
Thanks for your answer !
Regarding the Invalid Product Type message, I tried to export again the certificate and now it shows the correct vaccine. It seams to be solved and correctly shows Comirnaty.
Regarding the name appearing it is still in Greek letters. Did you manage to make it show the Latin version ?
I am using MacOS for generating the pass and iOS for storing it.

**Comment by marvinsxtr** [comment]
@Grendas It could be that the greek authorities had to update the medical product key and adjust it to the specification. CovidPass directly fetches the specification from the dcc project on GitHub so maybe that was the issue. If this problem is solved, I would close this now and refer to #46 for the name discussion.

**Comment by Grendas** [comment]
Alright, thanks a lot for your answers ! 😊
