### ISSUE TITLE
Android Passes / Google Pay support

### ISSUE THREAD

**Issue by DRSchlaubi** [covidpass-org/covidpass#45]
Even though .pkpass to Google pay converters exist, and they can work CovidPass passes using them is quite tedious, and it would be great to support this here as well

**Comment by JantsoP** [comment]
I used testing app called [WalletPasses](https://play.google.com/store/apps/details?id=io.walletpasses.android&hl=en&gl=US)
Worked directly with loaded .pkpass file.

**Comment by marvinsxtr** [comment]
Google is actively working on an integration of certificates, but only authorized organizations can use their API. See [this blog post](https://developers.googleblog.com/2021/06/google-updates-passes-api-to-save-covid-testing-and-vaccination-information-on-Android-devices.html).

**Comment by DRSchlaubi** [comment]
> Google is actively working on an integration of certificates, but only authorized organizations can use their API. See [this blog post](https://developers.googleblog.com/2021/06/google-updates-passes-api-to-save-covid-testing-and-vaccination-information-on-Android-devices.html).

Yeah, that integration probably won't be possible here, I've requested to reopen corona-warn-app/cwa-app-android#3486, as it got declined before the announcement of "Covid passes", but have no answer yet
