### ISSUE TITLE
Support test and recovery certificates

### ISSUE THREAD

**Issue by marvinsxtr** [covidpass-org/covidpass#5]

**Comment by mrMiimo** [comment]
this would be useful...

**Comment by marvinsxtr** [comment]
We would need example QR codes to debug this. Otherwise this should be easy to implement.

**Comment by mrMiimo** [comment]
I don't have one right now, but I can try and get one

**Comment by marvinsxtr** [comment]
Just found a [test certificate](https://www.biberach.de/fileadmin/Formulare/Kreisgesundheitsamt/02_t_ErikaMustermann.pdf) and a [pixelated recovery certificate](https://service.turbomed.de/download/05470843ff65b40e56b6ceff431b6ff1) which we could try.

**Comment by Ein-Tim** [comment]
@marvinsxtr Does it matter that both examples don't have a valid signature?

**Comment by marvinsxtr** [comment]
Not really, what's most important is that they are recognized by Corona-Warn-App or CovPass. Have you tried the recovery cert? @Ein-Tim

**Comment by Ein-Tim** [comment]
They are recognized but CovPass shows "COVID-Zertifikat enthält keine gültige Signatur" and CWA is not able to scan recovery or test certificates in version 2.4, this feature will be added in version 2.5...

**Comment by marvinsxtr** [comment]
That should suffice for our testing purposes.

**Comment by marvinsxtr** [comment]
We can use the [official dgc testdata repository](https://github.com/eu-digital-green-certificates/dgc-testdata) for testing purposes from now on as described in #33. The repository includes test data for countries like UK where this web app does not work with vaccination certificates either.

**Comment by marvinsxtr** [comment]
Closing this with reference to #34.
