### ISSUE TITLE
Show birthday instead of the country of vaccination

### ISSUE THREAD

**Issue by 10Meisterbaelle** [covidpass-org/covidpass#53]

**Comment by marvinsxtr** [comment]
Could you give a reason? @mackonsti proposed this change.

**Comment by mackonsti** [comment]
Ideally it would be great to have both, country of vaccination and (despite the lack of space) birth date. The reason I had mentioned it, is for the checks by _authorities_ that would cross-reference the passport or some ID. My [proposal was to add the country](https://github.com/covidpass-org/covidpass/issues/30#issuecomment-884904774) really, if space is enough (with date of birth).

One can argue that we may eventually need all the info found on the PDF issued by the member states (countries) but it's true that the date of birth is a more accurate item for verification than the country (which was written in the back).

@marvinsxtr as there are people that prefer _this_ and others _that_, ultimately you are the one who can decide as it is _your_ service/app that helps others for free. If you decide to revert to the date of birth, please do not remember to revert showing the Country too, in the back of the Wallet item 👍  Thanks

**Comment by 10Meisterbaelle** [comment]
> Could you give a reason? @mackonsti proposed this change.

Birthday is a bit more useful than the country of vaccination, also the verifier should not be able to know where you have been vaccinated.

**Comment by marvinsxtr** [comment]
Well, from a privacy perspective, I found that the date of birth is more sensitive than the country and should not be displayed on the front.

**Comment by 10Meisterbaelle** [comment]
> Well, from a privacy perspective, I found that the date of birth is more sensitive than the country and should not be displayed on the front.

But, first of all, the verifier sees the birthday anyways (by validating the certificate) and second of all: Both of them should be hidden in the hidden menu

**Comment by marvinsxtr** [comment]
I have reverted the change in #56. The date of birth is now also visible on the test and recovery certificates.

**Comment by mackonsti** [comment]
Thanks @marvinsxtr for the update. Did you keep the country in the back of the pass, like before?

**Comment by marvinsxtr** [comment]
@mackonsti Yes :)
