### ISSUE TITLE
Short version of the privacy policy

### ISSUE THREAD

**Issue by marvinsxtr** [covidpass-org/covidpass#59]
Something like

- Generated on your device
- Open source & transparent
- Hosted in the EU

**Comment by mackonsti** [comment]
I like the expanded version of the policy nevertheless, do keep it @marvinsxtr even under a link to a new page.

**Comment by Ein-Tim** [comment]
I'd suggest to also add some icons, like Twitter does: https://twitter.com/de/privacy

**Comment by marvinsxtr** [comment]
@mackonsti We have to keep the long version anyway by law.
@Ein-Tim I would suggest something like ✅ for the short version.

**Comment by marvinsxtr** [comment]
See #63.
