### ISSUE TITLE
Colors from Human Interface Guidelines

### ISSUE THREAD

**Issue by everdrone** [covidpass-org/covidpass#64]
Took the colors from the [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color) for iOS

The colors below are for the Light theme, we can also find the average color between the Light and Dark version so it suits every wallet more pleasantly but I'll open a PR with that if you like the idea.

This implies that new localized keys must be added

```ts
public static COLORS = {
  white:     'rgb(255, 255, 255)',
  black:     'rgb(0,   0,   0)',
  darGrey:   'rgb(44,  44,  46)',
  lightGrey: 'rgb(142, 142, 147)',

  red:       'rgb(255, 59,  48)',
  orange:    'rgb(255, 149, 0)',
  yellow:    'rgb(255, 204, 0)',
  green:     'rgb(52,  199, 89)',
  mint:      'rgb(0,   199, 190)',
  teal:      'rgb(48,  176, 199)',
  cyan:      'rgb(50,  173, 230)',
  blue:      'rgb(0,   122, 255)',
  indigo:    'rgb(88,  86,  214)',
  purple:    'rgb(175, 82,  222)',
  pink:      'rgb(255, 45,  85)',
  brown:     'rgb(162, 132, 94)',
}
```

**Comment by marvinsxtr** [comment]
Thank you for the suggestion, I think the Light theme (which apparently means the colors are darker) is more suitable because the colors do not look as much like neon colors. We would have to see if yellow is readable but other than that, I think it's okay to switch from material colors to Apples colors because it's mostly used on iOS anyway.

**Comment by marvinsxtr** [comment]
We could also take a look at the accessible color palette (see the accessible tab at the link you provided), because readability is most important for a pass. That's also why I chose darker colors which are well readable with white text on them.

**Comment by everdrone** [comment]
I was thinking since there are many options now maybe we could add the color to the list, like a tiny square or a colored background inside the dropdown menu?

When generating my pass I downloaded all of them to decide later the one I liked the most

**Comment by marvinsxtr** [comment]
This would mean that we have to write our own dropdown menu and can't use the native one I assume. We could maybe use something like this: https://headlessui.dev/react/menu.

**Comment by hauketoenjes** [comment]
I would propose something like this:

White mode: https://dribbble.com/shots/14510224-Cards-White-UI
Dark mode: https://dribbble.com/shots/14630755-Cards-Dark-UI

Pictures below:
![image](https://user-images.githubusercontent.com/25830076/127287974-fafaf1c3-96ba-4d5b-9983-605f22fe0593.png)
![image](https://user-images.githubusercontent.com/25830076/127288039-2d179ab7-ab94-46f7-801b-92e744baf2c7.png)

That would remove the dropdown menu and the colors can be seen when selecting them. Should be possible with headlessui. I will look into that.

**Comment by hauketoenjes** [comment]
This is what I would suggest. This is currently with the old colors and multiple times the same color to show how wrapping works on smaller devices.

See commit 11d739b

![image](https://user-images.githubusercontent.com/25830076/127321587-72cb694a-ffa5-4132-bb00-2c079062bd90.png)

**Comment by marvinsxtr** [comment]
See #70. Just noticed we don't even need the translation keys anymore.

**Comment by marvinsxtr** [comment]
> Just noticed we don't even need the translation keys anymore.
We should maybe add them as alt text for colorblind people.
