### ISSUE TITLE
Only send the manifest.json to the server for signing and assemble the pass locally

### ISSUE THREAD

**Issue by marvinsxtr** [covidpass-org/covidpass#7]
It may be possible to save a lot of data which has to be sent to the server by generating the contents of the pass file locally and only sending the manifest with the hashes to the server, where it is signed.

**Comment by marvinsxtr** [comment]
@KhaosT Thank you for your contribution! I looked into this and found some things to consider here.

If we only check the manifest.json, in theory everyone could generate any Apple Wallet pass. See [this excerpt](https://developer.apple.com/forums/thread/48719?answerId=150126022#150126022) from the Apple Developer Agreement.

To preserve the trademark, I suggest checking against the icon/logo hash on the server side. In order to preserve other static content of the pass, we would have to modify the structure of the pkpass file in some way, e.g by adding a json file of which we again check the hash on the server.

Another concern is that we do not verify the validity of the created vaccination certificate at the moment. This is something we would also have to do on the server and need the QR Code data for I believe.

The best compromise would be to have the user opt in to validate the pass. In this case, the data would be sent to the server for validation and pass generation. If they opt out however, we would generate the pass in the browser and only check against the trademark and some static content if possible (e.g. a visible hint that the certificate may be invalid).

I am looking forward to your and the others ideas on this.

**Comment by marvinsxtr** [comment]
> To preserve the trademark, I suggest checking against the icon/logo hash on the server side.

I pushed it in this configuration now.

**Comment by hauketoenjes** [comment]
Hi, 

we transitioned the frontend to the [new API](https://github.com/covidpass-org/CovidPassApiNet) written in C#.

The frontend generates the whole pass and only send the hashed `pass.json` to the server. This also includes the information about color because the icon hashes are different (either black or white icons).
