### ISSUE TITLE
Does not work in iPad Air 4th generation 

### ISSUE THREAD

**Issue by ManfredKohl** [covidpass-org/covidpass#74]
IOS 14.7.1
recognises QR code ok (from camera or file) but after selecting add to wallet reproducible message:
"Safari cannot download this file"

![CovidPass png](https://user-images.githubusercontent.com/56868383/128019157-fa3cf35b-d882-47c8-9c6b-1f48a0d70a75.jpg)

**Comment by marvinsxtr** [comment]
As far as I know, the iPad does not really have the wallet app or the integration is incomplete. Can you try it on your iPhone instead?

**Comment by ManfredKohl** [comment]
I confirm works perfectly on iphone.
iPad has wallet but probably slightly differently implemented as you said
