### ISSUE TITLE
Possibility to make QR larger in size?

### ISSUE THREAD

**Issue by gregory-villmann** [covidpass-org/covidpass#75]
Using iPhone 11, the QR seems to be rather small. The Estonian government has came up with a website https://kontroll.digilugu.ee/ to test the validity of the passes. The website can not scan my wallet code as it's too small on my phone... Is there a possibility to make the QR larger?

**Comment by laurazard** [comment]
As far as I know, the .pkpass/wallet pass format does not allow the size/style of anything to be customized, which is quite unfortunate but not something that can be addressed by anyone outside apple.

**Comment by marcelpietsch** [comment]
It seems that the problem lies in the complexity of the QR code, which makes it's individual pixels rather small. I don't think that the image container can be made bigger, as the wallet pass templates from Apple dictate that area's sizing.

Take a look at the examples over here: https://www.passcreator.com/de

**Comment by marvinsxtr** [comment]
A possible solution is to embed a link into the pass fields which contains the complete QR Code data and can be displayed bigger in a Browser. Got the idea from https://coronapass.fabianpimminger.de

**Comment by marcelpietsch** [comment]
But where would the QR code image file be hosted in that case?

**Comment by marvinsxtr** [comment]
The file would not be hosted anywhere as that would be a huge privacy issue. As far as I understood, it is passed as an URL parameter.

**Comment by marcelpietsch** [comment]
That's what I was going for. Right, converting it to base64 makes sense. This could help.

https://github.com/renanbastos93/image-to-base64

**Comment by marvinsxtr** [comment]
I think converting the actual payload to base64 is better. I bet there is some JavaScript library which can display a QR code from a payload.

**Comment by laurazard** [comment]
If I'm understanding the proposed approach correctly, this would only work for as long as the user has an active internet connection, therefore limiting its usability -- especially considering one might be required to show this at airports, different countries, etc. when traveling where one might not immediately have an internet connection. I wonder if it wouldn't be simpler to just have a link to open a webview with the base64 encoded image.

**Comment by marvinsxtr** [comment]
If Safari can natively show the image when it's passed as a url param, I would also support encoding the image instead of the payload.

**Comment by marvinsxtr** [comment]
Just noticed that opening a link in the pass only works when opening the actual wallet app and not when using the double press on the power button. Which makes sense because Safari is not available from lock screen. Kinda defeats the purpose of having the pass in the wallet.

**Comment by Ein-Tim** [comment]
@dotsam 

What the MacRumors article mentions is the extension of verifiable health records to also support COVID-19 vaccinations and test results with the option to also store certificates in the Wallet directly from the health app (where the verifiable health records are stored).

However, this does not improve the situation we have here, as currently the EU digital COVID certificate system is in use all across Europe, but verifiable health records are only available for organizations that issue [SMART Health Cards](https://smarthealth.cards/).
This is another standard and has nothing to do with the system in use here.

However, maybe Apple adds a new QR-Code size for this kind of card, not only for "their" COVID-19 vaccination and test certificates which are stored through the health app but for all developers.
If this is the case it would probably be an easy task to adjust the QR code size to the bigger one. 

I hope I didn't mix up anything here 😅

**Comment by janbrasna** [comment]
I'm not sure if Safari is the handler app for `data:` protocol, or if such link would be recognized and enabled as a link in the first place. (Otherwise yes, Safari gladly opens inline `data:` base64 content/images without issues.)

Let's just hope the 15.1 coming out of beta any given day 🤞 brings us bigger QR code layout options.

**Comment by marvinsxtr** [comment]
The larger QR code can now be viewed by tapping on the link on the back of the pass (when opening the actual Wallet app and with internet connection). See #142 Unfortunately, Safari does not open `data:` URLs from the Wallet app.

**Comment by marvinsxtr** [comment]
As there is no better solution to this problem atm, I will close this for now.
