### ISSUE TITLE
Warn the user when not using Safari

### ISSUE THREAD

**Issue by MarcAnt01** [covidpass-org/covidpass#76]
First of all, thanks for your project, having the pass in the wallet is so handy.
Atm there's just a texture saying to use Safari, but I haven't seen it in my first try and was wondering why your site wasn't adding the pass to the wallet since no warning was being shown.
I'd suggest a browser detection and a browser warning should appear when using it in another browser, so that the user is aware of it.

**Comment by marvinsxtr** [comment]
I already implemented the detection for Chrome and haven't found a way to just warn for every browser other than Safari.

**Comment by MarcAnt01** [comment]
So are you planning to implement a detection for each browser? I use Edge here and nothing was being shown

**Comment by marvinsxtr** [comment]
Probably not each and every browser but the most popular ones would be favorable.

**Comment by vic60400** [comment]
`var isSafari = navigator.vendor && navigator.vendor.indexOf('Apple') > -1 &&
                   navigator.userAgent &&
                   navigator.userAgent.indexOf('CriOS') == -1 &&
                   navigator.userAgent.indexOf('FxiOS') == -1;
`
This should be enought.

**Comment by marvinsxtr** [comment]
Implemented this in #128
