### ISSUE TITLE
Portuguese QR code not recognized

### ISSUE THREAD

**Issue by souocare** [covidpass-org/covidpass#77]
Hi! Portuguese QR code are not recognized. Is there any way you could update to work with Portuguese QR codes? I can send an example if needed.

**Comment by laurazard** [comment]
That's interesting, I'm Portuguese and it recognizes mine. Regardless, the https://github.com/eu-digital-green-certificates/dgc-testdata dgc datasets should be enough to test, but maybe it's an issue with your specific QR code somehow?

**Comment by souocare** [comment]
Well, I managed to make it work. For me, it didn't work with the original PDF. So, I had to screenshot only the QR Code, convert the image to pdf and import it. 
Thanks!
