### ISSUE TITLE
Test result: not detected

### ISSUE THREAD

**Issue by silviagreen** [covidpass-org/covidpass#79]
The pass generated using the qr code with negative covid test result shows:

Test result: not detected

instead of negative

**Comment by Ein-Tim** [comment]
Not detected is correct, CWA also shows "not detected". 

It means that the virus wasn't detected. I know, kinda confusing 😅

**Comment by marvinsxtr** [comment]
We may change to "Positive" / "Negative" if that's more intuitive.

**Comment by HLFH** [comment]
Same issue. Standard on test results is "negative"/"positive". "Not detected" seems like "inconclusive" which is an issue if we want to use this app.

**Comment by marvinsxtr** [comment]
Fixed with #141
