### ISSUE TITLE
Add support for sharing

### ISSUE THREAD

**Issue by kamil98** [covidpass-org/covidpass#8]
Hi, I wanted to generate passes for my family but they cannot be shared. Is that intentional?

All of the other passes in my wallet have the sharing button. 

Here are some (redacted) screenshots:
![A67B9A3E-4413-4AE7-A07C-2809C69E2538](https://user-images.githubusercontent.com/15572959/123559062-1f009780-d79a-11eb-99a8-f725adf2212c.jpeg)
![39C73534-F778-4D19-BD5A-01209C6DAAB2](https://user-images.githubusercontent.com/15572959/123559065-20ca5b00-d79a-11eb-8a0b-99f091538ce7.jpeg)

You can see that the sharing button isn’t available on the covid pass 😢

**Comment by hauketoenjes** [comment]
Hi, we enabled the sharing feature again, we didn't think about the use case.
