### ISSUE TITLE
How to remove from iOS wallet

### ISSUE THREAD

**Issue by itsSAL16** [covidpass-org/covidpass#83]
There’s no option to remove it from Apple’s wallet (iOS 14.7.1)

**Comment by itsSAL16** [comment]
For me there isn’t this option

![Uploading C305B6B5-5B03-4558-B33F-8DDE65E17511.jpeg…]()

**Comment by itsSAL16** [comment]
![38D7FD1E-0ECD-4626-B01C-E51A0605B150](https://user-images.githubusercontent.com/88834858/129200847-5e4833ba-bac5-4a12-ab7a-8011ad0f1819.jpeg)

for me there isn’t this option

**Comment by Ein-Tim** [comment]
@itsSAL16 Did you open the Apple Wallet App?

**Comment by itsSAL16** [comment]
> @itsSAL16 Did you open the Apple Wallet App?

It was this, I believed I could edit it by double tapping power button. Thanks
