### ISSUE TITLE
Is it normal that the QR Code generated does not look the same ?

### ISSUE THREAD

**Issue by LukasAppleFan** [covidpass-org/covidpass#88]
Hi,
I live in France and I just got the Covid Pass !
After using CovidPass I can see that the QR Code does not look the same as the one on the paper and the one generated in TousAntiCovid (French Covid app).
But all three pass seem to be working with TAC Verif (French app for professional to check COVID Pass validity). The app could see my name and birthdate (it still showed all three n’as invalid because it’s not been 7 days yet).
Thanks

**Comment by hauketoenjes** [comment]
Hi, 

That behavior is totally normal. The reason why the QR Codes are different in different apps is the different error correction level they use. The data inside the QR code is the same, but they look different.

For additional information:
- [QR Code Error Correction](https://en.wikipedia.org/wiki/QR_code#Error_correction)
- [German "Corona Warn App" Issue about this](https://github.com/corona-warn-app/cwa-documentation/issues/641)

**Comment by LukasAppleFan** [comment]
Ok thanks a lot for your reply
