### ISSUE TITLE
QR Code support international

### ISSUE THREAD

**Issue by GabrielCartier** [covidpass-org/covidpass#92]
Hello, Canadian here. Our vaccination passport is going live in a week or so and like other countries, the app offered does not allow the usage of the wallet.

I was wondering if there is any plan to support international QR code. 

Actually, I'd be interested in knowing a bit more about where the decoding is being done and what are the limitations or how to implement support for Canadian code. If someone would give me some pointers I can certainly open a PR.

Thanks

**Comment by Lapsusone** [comment]
Will COVIDPass ever support other QR codes than the European one? Or should we fork the repo?

Regarding the Canadian QR code, here’s a [project](https://github.com/hackfestca/hf-qrcode)  that shows how to read it.

**Comment by JantsoP** [comment]
This might be a bit hard to do, since there is no global standard for this system. As mentioned above, Canada has own, idk about US or LATAM or Africa/Asia region. And if all of them would have their own standard, it would be hell to upkeep. Just giving my two cents on this.

**Comment by kmavai** [comment]
I believe BC and Quebec in Canada use the Smart Health Cards. More info on it [here](https://github.com/smart-on-fhir/health-cards/blob/main/docs/index.md) and [here](https://smarthealth.cards). I was able to scan the BC QR code with iOS 15 beta and add it into my Health app as a vaccine record. It also has a copy of the QR code, but it's not very easily accessible compared to the Wallet app.

One thing I haven't been able to find is if the Wallet app QR codes support the type of QR code needed for the vaccine records. Need to do some more digging around.

**Comment by Lapsusone** [comment]
> This might be a bit hard to do, since there is no global standard for this system. As mentioned above, Canada has own, idk about US or LATAM or Africa/Asia region. And if all of them would have their own standard, it would be hell to upkeep. Just giving my two cents on this.

I believe there are ways to structure the code such that each country has it’s own code file with the QR code logic, but that’s more about the project’s vision. Right now the description is 
> Web app for adding EU Digital COVID Certificates to your wallet apps

If that’s not changing then better fork it.

**Comment by Lapsusone** [comment]
I have found [this fork](https://github.com/flochtililoch/covidpass) that works with passes using Smart Health Card format. Works in QC (ON and BC too?) @GabrielCartier @kmavai
