### ISSUE TITLE
Not working with Google Pay app on Android

### ISSUE THREAD

**Issue by MrZyr0** [covidpass-org/covidpass#99]
I've tested this app on my OnePlus 7 Pro under OxygenOS (android 11) and Chrome web browser to import my EU COVID-19 certificate but it result only on downoad a small file impossible to read with no apps.

Is anyone have an idea ? Is this project support Android and Google Pay ?

Thank you for your help

**Comment by hauketoenjes** [comment]
Hi, 

The file that is being downloaded is a `.pkpass` file, which is natively supported by Apple Wallet. It is not supported by Google Pay natively.

However, there are a few apps in the Play Store to open and show `.pkpass` files. If you want to use one of those, you can import the downloaded file there. Another way is to use a tool to import the file into Google Pay.
